version: "3"
services:
  web-appsmith:
     image: index.docker.io/appsmith/appsmith-ee
     container_name: appsmith
     ports:
       - "81:80"
       - "444:443"
     volumes:
         - ./stacks:/appsmith-stacks
     restart: unless-stopped
