services:
  nginx:
    image: nginx:alpine
    restart: always  
    container_name: nginx
    ports:
      - "80:80"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web

networks:
  web:
    external: true
