networks:
  web:
    external: true  

volumes:
  pgdata:

services:

  web-wiki-db:
    image: postgres:15
    container_name: wikijs-db
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijsrocks
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web    

  web-wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    depends_on:
      - web-wiki-db
    restart: always
    environment:
      DB_TYPE: postgres
      DB_HOST: web-wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    networks:
      - web  
